import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Share2, 
  Download, 
  FileText, 
  Copy, 
  Check, 
  Loader2,
  FileJson,
  ClipboardList
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';
import { ExcelFile, ParsedData } from '@/lib/excel-parser';
import { DataQualityReport } from '@/lib/data-quality';
import { AIInsight } from '@/hooks/useAIInsights';
import { ChartConfig, SavedDashboard } from '@/lib/dashboard-storage';

interface ShareExportPanelProps {
  fileName: string;
  sheet: ParsedData;
  qualityReport: DataQualityReport;
  insights: AIInsight[];
  chartConfigs: ChartConfig[];
}

export function ShareExportPanel({
  fileName,
  sheet,
  qualityReport,
  insights,
  chartConfigs,
}: ShareExportPanelProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  // Generate insight summary text
  const generateInsightSummary = useCallback(() => {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    let summary = `# Data Analysis Report\n`;
    summary += `**File:** ${fileName}\n`;
    summary += `**Generated:** ${date}\n`;
    summary += `**Data Quality Score:** ${qualityReport.overallScore}/100\n\n`;

    summary += `## Dataset Overview\n`;
    summary += `- **Rows:** ${sheet.rowCount.toLocaleString()}\n`;
    summary += `- **Columns:** ${sheet.columnCount}\n`;
    summary += `- **Numeric Columns:** ${sheet.columns.filter(c => c.type === 'number').length}\n`;
    summary += `- **Text Columns:** ${sheet.columns.filter(c => c.type === 'string').length}\n\n`;

    if (qualityReport.issues.length > 0) {
      summary += `## Data Quality Issues\n`;
      qualityReport.issues.slice(0, 5).forEach(issue => {
        summary += `- **${issue.severity.toUpperCase()}:** ${issue.message}\n`;
      });
      summary += '\n';
    }

    if (insights.length > 0) {
      summary += `## AI-Generated Insights\n`;
      insights.slice(0, 5).forEach((insight, i) => {
        summary += `${i + 1}. ${insight.text}\n`;
        if (insight.explanation) {
          summary += `   _${insight.explanation}_\n`;
        }
      });
      summary += '\n';
    }

    summary += `## Charts Generated\n`;
    chartConfigs.forEach((config, i) => {
      summary += `${i + 1}. ${config.title || `${config.type} chart`} - ${config.aggregation} of ${config.yAxis} by ${config.xAxis}\n`;
    });

    summary += `\n---\n_Generated by DataViz Pro_`;

    return summary;
  }, [fileName, sheet, qualityReport, insights, chartConfigs]);

  // Export as PDF
  const exportAsPDF = useCallback(async () => {
    setIsExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      
      const summary = generateInsightSummary();
      const lines = summary.split('\n');
      
      let y = 20;
      const lineHeight = 7;
      const margin = 20;
      const pageWidth = doc.internal.pageSize.width;
      
      lines.forEach(line => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        
        // Handle headers
        if (line.startsWith('# ')) {
          doc.setFontSize(18);
          doc.setFont('helvetica', 'bold');
          doc.text(line.replace('# ', ''), margin, y);
          y += lineHeight * 2;
        } else if (line.startsWith('## ')) {
          doc.setFontSize(14);
          doc.setFont('helvetica', 'bold');
          doc.text(line.replace('## ', ''), margin, y);
          y += lineHeight * 1.5;
        } else if (line.startsWith('**')) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'bold');
          const cleanLine = line.replace(/\*\*/g, '');
          doc.text(cleanLine, margin, y);
          y += lineHeight;
        } else if (line.startsWith('- ') || line.startsWith('  ')) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const cleanLine = line.replace(/\*\*/g, '').replace(/_/g, '');
          const splitText = doc.splitTextToSize(cleanLine, pageWidth - margin * 2);
          doc.text(splitText, margin + 5, y);
          y += lineHeight * splitText.length;
        } else if (line.match(/^\d+\./)) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const cleanLine = line.replace(/_/g, '');
          const splitText = doc.splitTextToSize(cleanLine, pageWidth - margin * 2 - 5);
          doc.text(splitText, margin + 5, y);
          y += lineHeight * splitText.length;
        } else if (line.trim()) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          doc.text(line, margin, y);
          y += lineHeight;
        } else {
          y += lineHeight * 0.5;
        }
      });

      doc.save(`${fileName.replace(/\.[^/.]+$/, '')}_report.pdf`);
      toast.success('Report exported as PDF');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    } finally {
      setIsExporting(false);
    }
  }, [generateInsightSummary, fileName]);

  // Export dashboard config as JSON
  const exportAsJSON = useCallback(() => {
    const config = {
      fileName,
      currentVersion: 1,
      exportedAt: new Date().toISOString(),
      charts: chartConfigs,
    };

    const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName.replace(/\.[^/.]+$/, '')}_dashboard.json`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success('Dashboard config exported as JSON');
  }, [fileName, chartConfigs]);

  // Copy summary to clipboard
  const copyToClipboard = useCallback(async () => {
    const summary = generateInsightSummary();
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    toast.success('Summary copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  }, [generateInsightSummary]);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Share2 className="w-4 h-4" />
          Share
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuItem onClick={exportAsPDF} disabled={isExporting} className="cursor-pointer">
          {isExporting ? (
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
          ) : (
            <FileText className="w-4 h-4 mr-2" />
          )}
          Export Report as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsJSON} className="cursor-pointer">
          <FileJson className="w-4 h-4 mr-2" />
          Export Dashboard Config
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={copyToClipboard} className="cursor-pointer">
          <AnimatePresence mode="wait">
            {copied ? (
              <motion.div
                key="check"
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                exit={{ scale: 0 }}
              >
                <Check className="w-4 h-4 mr-2 text-chart-5" />
              </motion.div>
            ) : (
              <motion.div
                key="copy"
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                exit={{ scale: 0 }}
              >
                <Copy className="w-4 h-4 mr-2" />
              </motion.div>
            )}
          </AnimatePresence>
          Copy Summary to Clipboard
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
